language: node_js
node_js: node

notifications:
  email:
    on_success: never
    on_failure: always

jobs:
  include:
    - stage: Deploy
      install:
        - npm install --save-dev vuepress
      script:
        - npm run docs:build
      after_success:
        - mv README.md LICENSE docs/.vuepress/dist --verbose
      deploy:
        skip-cleanup: true
        verbose: true
        provider: pages
        github-token: $GITHUB_TOKEN
        repo: OOP-course/oop-course.github.io
        target-branch: master
        committer_from_gh: true
        local-dir: docs/.vuepress/dist
        on:
          branch: master
